version: "3.5"
services:
 mysql-server:
  image: mysql
  restart: unless-stopped
  container_name: mysql-server
  ports:
    - 3307:3306
  environment:
    MYSQL_ROOT_PASSWORD: z4bb1x
    MYSQL_DATABASE: zabbix
    MYSQL_USER: zabbix
    MYSQL_PASSWORD: z4bb1x
    DB_SERVER_DBNAME: zabbix
  command:
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_bin
  # secrets:
  #  - MYSQL_DATABASE
  #  - MYSQL_USER
  #  - MYSQL_PASSWORD
  #  - MYSQL_ROOT_PASSWORD
  #  - DB_SERVER_DBNAME
  volumes:
    - mysql_volume:/varlib/mysql
  networks:
    - zabbix-net

 zabbix-java-gateway:
  image: zabbix/zabbix-java-gateway:alpine-6.4-latest
  container_name: zabbix-java-gateway
  networks:
    - zabbix-net

 zabbix-server-mysql:
  image: zabbix/zabbix-server-mysql
  restart: unless-stopped
  container_name: zabbix-server-mysql
  ports:
   - "10051:10051"
  environment:
    MYSQL_ROOT_PASSWORD: z4bb1x
    MYSQL_DATABASE: zabbix
    MYSQL_USER: zabbix
    MYSQL_PASSWORD: z4bb1x
    DB_SERVER_DBNAME: zabbix
  secrets:
  #  - DB_SERVER_HOST
  #  - MYSQL_DATABASE
  #  - MYSQL_USER
  #  - MYSQL_PASSWORD
  #  - MYSQL_ROOT_PASSWORD
   - ZBX_JAVAGATEWAY
   - DB_SERVER_DBNAME
  networks:
    - zabbix-net

 zabbix-agent:
  image: zabbix/zabbix-agent 
  container_name: zabbix-agent
  ports:
   - "10050:10050"
  secrets:
   - ZBX_SERVER_HOST
  networks:
   - zabbix-net

 zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:alpine-6.4-latest
  container_name: zabbix-snmptraps
  ports:
   - "162:1162/udp"
  volumes:
   - /zbx_instance/snmptraps:/var/lib/zabbix/snmptraps:rw
   - /var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
  networks:
   - zabbix-net

 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:ubuntu-6.4-latest
  restart: always
  container_name: zabbix-web-nginx-mysql
  ports:
   - "80:8080"
   - "443:8443"
  environment:
    MYSQL_ROOT_PASSWORD: z4bb1x
    MYSQL_DATABASE: zabbix
    MYSQL_USER: zabbix
    MYSQL_PASSWORD: z4bb1x
    DB_SERVER_DBNAME: zabbix
  depends_on:
   - mysql-server
  secrets:
   - ZBX_SERVER_HOST
   - DB_SERVER_HOST
  #  - MYSQL_DATABASE
  #  - MYSQL_USER
  #  - MYSQL_PASSWORD
  #  - MYSQL_ROOT_PASSWORD
  #  - DB_SERVER_DBNAME
  networks:
   - zabbix-net

networks:
  zabbix-net:
    name: zabbix-net
    external: true

volumes:
  snmptraps:
  mysql_volume:

secrets:
  DB_SERVER_HOST:
    file: ./env/.DB_SERVER_HOST
  MYSQL_USER:
    file: ./env/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./env/.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./env/.MYSQL_ROOT_PASSWORD
  MYSQL_DATABASE:
    file: ./env/.MYSQL_DATABASE
  ZBX_ENABLE_SNMP_TRAPS:
    file: ./env/.ZBX_ENABLE_SNMP_TRAPS
  ZBX_JAVAGATEWAY:
    file: ./env/.ZBX_JAVAGATEWAY
  ZBX_SERVER_HOST:
    file: ./env/.ZBX_SERVER_HOST
  DB_SERVER_DBNAME:
    file: ./env/.DB_SERVER_DBNAME
